NPLPackages/main

- script/apps/WebServer/admin/wp-content/pages/wiki/auth/clientconfig.page
- script/apps/WebServer/admin/wp-content/pages/wiki/controllers/githubService.js
- script/apps/WebServer/admin/wp-content/pages/wiki/controllers/userReposController.js
- script/apps/WebServer/admin/wp-content/pages/wiki/partials/userRepos.html
> github service added

- script/apps/WebServer/admin/wp-content/pages/db_manager.page
TableDatabase网页简易客户端，选定db文件所在目录，即可列出相关db文件(数据表)，具有基本的增删查改，列出当前已索引的字段等基本功能，查询过滤字段的值支持json串,如_id = {"gt":2}查询所有_id大于2的记录，暂未实现自动分页，需手动在过滤条件中设置记录数限制，否则获取全部记录。
> tableDB查看器

- script/apps/WebServer/admin/wp-content/pages/db_manager.page
> 编辑记录使用文本模式

- script/apps/WebServer/admin/wp-content/pages/localInstall.page
- script/apps/WebServer/admin/wp-content/pages/wiki/mod/packages/pages/index.page
update localInstall and index pages
> update localInstall and index pages 

- script/ide/System/Scene/Assets/ParaXModelAttr.lua
> 添加ParaXModel导出x文件的函数接口

- script/ide/System/Database/Collection.lua
- script/ide/System/Database/StorageProvider.lua
- script/ide/System/Database/TableDatabase.lua
- script/ide/System/Database/test/test_TableDatabase.lua
issue 11 in TableDB, the api is both test for tableDB and raft tabledb
@LiXizhi
> issue 11 in TableDB

- script/ide/System/Plugins/PluginLoader.lua
fix PluginLoader in wikicraft environment
> fix PluginLoader in wikicraft environment

- script/ide/System/Windows/Controls/TextControl.lua
- script/ide/System/Windows/UIElement.lua
- script/ide/System/Windows/mcml/Elements/pe_button.lua
- script/ide/System/Windows/mcml/Elements/pe_checkbox.lua
- script/ide/System/Windows/mcml/Elements/pe_container.lua
- script/ide/System/Windows/mcml/Elements/pe_div.lua
- script/ide/System/Windows/mcml/Elements/pe_editbox.lua
- script/ide/System/Windows/mcml/Elements/pe_identicon.lua
- script/ide/System/Windows/mcml/Elements/pe_radio.lua
- script/ide/System/Windows/mcml/Elements/pe_sliderbar.lua
- script/ide/System/Windows/mcml/Elements/pe_textarea.lua
- script/ide/System/Windows/mcml/PageElement.lua
1.多行文本添加光标行效果
2.修改页面控件位置大小同步到底层控件方式
> 修改页面控件位置大小同步到底层控件方式

- script/ide/System/Database/Collection.lua
- script/ide/System/Database/IOThread.lua
- script/sqlite/sqlite3.lua
> TableDB injectWALPage support

- NPLPackageMain.csproj
- script/ide/STL/List.lua
- script/ide/System/Core/ToolBase.lua
- script/ide/System/Windows/Controls/ListBox.lua
- script/ide/System/Windows/Controls/ListView.lua
- script/ide/System/Windows/Controls/MultiLineEditbox.lua
- script/ide/System/Windows/Controls/Primitives/ScrollAreaBase.lua
- script/ide/System/Windows/Controls/ScrollArea.lua
- script/ide/System/Windows/Controls/TextControl.lua
- script/ide/System/Windows/Controls/TreeNode.lua
- script/ide/System/Windows/Controls/TreeView.lua
- script/ide/System/Windows/UIElement.lua
- script/ide/System/Windows/UIElement_p.lua
- script/ide/System/Windows/Window.lua
- script/ide/System/Windows/mcml/Elements/pe_container.lua
- script/ide/System/Windows/mcml/Elements/pe_div.lua
- script/ide/System/Windows/mcml/Elements/pe_scrollarea.lua
- script/ide/System/Windows/mcml/Elements/pe_treenode.lua
- script/ide/System/Windows/mcml/Elements/pe_treeview.lua
- script/ide/System/Windows/mcml/PageElement.lua
- script/ide/System/Windows/mcml/PageLayout.lua
- script/ide/System/Windows/mcml/mcml.lua
- script/ide/math/Rect.lua
- script/test/MCMLV2/mcml_window.html
1.pe_scrollarea 滚动窗口添加
2.pe_treeview  添加
> treeview控件实现

- NPLPackageMain.csproj
- script/ide/System/Windows/Controls/GridView.lua
- script/ide/System/Windows/Controls/Label.lua
- script/ide/System/Windows/Controls/ListBox.lua
- script/ide/System/Windows/Controls/MultiLineEditbox.lua
- script/ide/System/Windows/Controls/Primitives/ScrollAreaBase.lua
- script/ide/System/Windows/Controls/Primitives/SliderBase.lua
- script/ide/System/Windows/Controls/ScrollArea.lua
- script/ide/System/Windows/UIElement.lua
- script/ide/System/Windows/mcml/Elements/pe_bindingblock.lua
- script/ide/System/Windows/mcml/Elements/pe_checkbox.lua
- script/ide/System/Windows/mcml/Elements/pe_container.lua
- script/ide/System/Windows/mcml/Elements/pe_div.lua
- script/ide/System/Windows/mcml/Elements/pe_gridview.lua
- script/ide/System/Windows/mcml/Elements/pe_img.lua
- script/ide/System/Windows/mcml/Elements/pe_input.lua
- script/ide/System/Windows/mcml/Elements/pe_label.lua
- script/ide/System/Windows/mcml/Elements/pe_pager.lua
- script/ide/System/Windows/mcml/Elements/pe_radio.lua
- script/ide/System/Windows/mcml/Elements/pe_repeat.lua
- script/ide/System/Windows/mcml/Elements/pe_select.lua
- script/ide/System/Windows/mcml/Elements/pe_treenode.lua
- script/ide/System/Windows/mcml/Elements/pe_treeview.lua
- script/ide/System/Windows/mcml/PageElement.lua
- script/ide/System/Windows/mcml/mcml.lua
- script/ide/System/test/test_pe_gridview.html
- script/test/MCMLV2/mcml_window.html
2.添加pe:label pe:img
3.UIElement:pointInsideRectAndMask函数功能修改，现在还需要判断点是否在裁剪范围内
4.scrollareabase添加了滚动条policy，可以选择是否显示/隐藏滚动条
5.scrollareabase添加了wheelAllow属性，可以选择是否接受鼠标滚动
> 1.添加pe:gridview 控件

- NPLPackageMain.csproj
- script/ide/System/Core/Color.lua
- script/ide/System/Core/PainterContext.lua
- script/ide/System/Windows/Controls/Button.lua
- script/ide/System/Windows/Controls/Button_p.lua
- script/ide/System/Windows/Controls/DropdownListbox.lua
- script/ide/System/Windows/Controls/ScrollBar.lua
- script/ide/System/Windows/UIElement.lua
- script/ide/System/Windows/mcml/CssSelector.lua
- script/ide/System/Windows/mcml/CssSelectorItem.lua
- script/ide/System/Windows/mcml/Elements/pe_button.lua
- script/ide/System/Windows/mcml/Elements/pe_checkbox.lua
- script/ide/System/Windows/mcml/Elements/pe_div.lua
- script/ide/System/Windows/mcml/Elements/pe_gridview.lua
- script/ide/System/Windows/mcml/Elements/pe_pager.lua
- script/ide/System/Windows/mcml/Elements/pe_radio.lua
- script/ide/System/Windows/mcml/Elements/pe_style.lua
- script/ide/System/Windows/mcml/Elements/pe_treenode.lua
- script/ide/System/Windows/mcml/Page.lua
- script/ide/System/Windows/mcml/PageElement.lua
- script/ide/System/Windows/mcml/Style.lua
- script/ide/System/Windows/mcml/StyleDefault.lua
- script/ide/System/Windows/mcml/default_style.mcss
- script/ide/System/test/test_Windows.lua
- script/ide/System/test/test_css_page.html
- script/ide/System/test/test_css_style.css
- script/test/MCMLV2/main.lua
- script/test/MCMLV2/mcml_window.html
2.提取代码中控件默认样式到外部默认mcss文件（script/ide/System/Windows/mcml/default_style.mcss）
> 控件添加默认多边形背景效果

- script/ide/System/Windows/mcml/Elements/pe_div.lua
> 修复pe:div 背景不能显示的bug

- script/ide/System/Windows/mcml/PageElement.lua
> 修复“align”属性显示错误的bug

- script/ide/System/Windows/mcml/Elements/pe_img.lua
> 修复pe_img错误的bug

- script/ide/System/Windows/mcml/Elements/pe_button.lua
- script/ide/System/Windows/mcml/Elements/pe_custom.lua
- script/ide/System/Windows/mcml/Elements/pe_div.lua
pe_div pe_button 支持 dynamic onclick
> pe_div pe_button 支持 dynamic onclick

- script/ide/System/Windows/mcml/Elements/pe_bindingblock.lua
- script/ide/System/Windows/mcml/Elements/pe_button.lua
- script/ide/System/Windows/mcml/Elements/pe_checkbox.lua
- script/ide/System/Windows/mcml/Elements/pe_container.lua
- script/ide/System/Windows/mcml/Elements/pe_div.lua
- script/ide/System/Windows/mcml/Elements/pe_font.lua
- script/ide/System/Windows/mcml/Elements/pe_if.lua
- script/ide/System/Windows/mcml/Elements/pe_input.lua
- script/ide/System/Windows/mcml/Elements/pe_label.lua
- script/ide/System/Windows/mcml/Elements/pe_radio.lua
- script/ide/System/Windows/mcml/Elements/pe_repeat.lua
- script/ide/System/Windows/mcml/Elements/pe_scrollarea.lua
- script/ide/System/Windows/mcml/Elements/pe_span.lua
- script/ide/System/Windows/mcml/Elements/pe_textarea.lua
- script/ide/System/Windows/mcml/Elements/pe_treenode.lua
fixed pe:gridview  childnode onclick function bug
> fixed pe:gridview  childnode onclick function bug

- script/ide/System/Database/SqliteIndexTable.lua
> fix issue #180 tableDB  index update bug

- script/ide/System/Windows/Controls/EditBox.lua
- script/ide/System/Windows/Controls/MultiLineEditbox.lua
- script/ide/System/Windows/Controls/TextControl.lua
- script/ide/System/Windows/MouseEvent.lua
- script/ide/System/Windows/mcml/Elements/pe_editbox.lua
- script/ide/System/Windows/mcml/Elements/pe_textarea.lua
1.pe_text,pe_textarea add "EmptyText" attribute
script\ide\System\Windows\Controls\MultiLineEditbox.lua
script\ide\System\Windows\Controls\TextControl.lua
script\ide\System\Windows\mcml\Elements\pe_editbox.lua
script\ide\System\Windows\mcml\Elements\pe_textarea.lua
2.editbox,multilineEditbox add double click select word and triple click select line
script\ide\System\Windows\Controls\EditBox.lua
script\ide\System\Windows\Controls\TextControl.lua
script\ide\System\Windows\MouseEvent.lua
> add "EmptyText" atrribute , double click select word, triple click select line

- script/ide/System/Core/UniString.lua
script\ide\System\Core\UniString.lua
> add the missing file UniString.lua
